//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TweetLocalizationEF
{
    using System;
    using System.Collections.Generic;
    
    public partial class alternateNames2
    {
        public int alternateNameId { get; set; }
        public Nullable<int> geoNameId { get; set; }
        public string isoLanguage { get; set; }
        public string alternateName { get; set; }
        public Nullable<int> isPrefferedName { get; set; }
        public Nullable<int> isShortName { get; set; }
        public Nullable<int> isColloquial { get; set; }
        public Nullable<int> isHistoric { get; set; }
    
        public virtual GeoNamesRestricted GeoNamesRestricted { get; set; }
    }
}
