//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TweetLocalizationEF
{
    using System;
    using System.Collections.Generic;
    
    public partial class countryResolutionOutcome
    {
        public int countryResolutionId { get; set; }
        public int tweetRandomSample_Id { get; set; }
        public string country1 { get; set; }
        public string country2 { get; set; }
        public string country3 { get; set; }
        public string country4 { get; set; }
        public string country5 { get; set; }
        public string country6 { get; set; }
        public string country7 { get; set; }
        public string country8 { get; set; }
        public string country9 { get; set; }
        public string country10 { get; set; }
        public string country11 { get; set; }
        public string country12 { get; set; }
        public string country13 { get; set; }
        public string country14 { get; set; }
        public string country15 { get; set; }
        public string country16 { get; set; }
        public string country17 { get; set; }
        public string country18 { get; set; }
    
        public virtual tweetRandomSample tweetRandomSample { get; set; }
    }
}
