//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TweetLocalizationEF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Retweets
    {
        public int id { get; set; }
        public long tweetid { get; set; }
        public string username { get; set; }
        public double @long { get; set; }
        public double lat { get; set; }
        public System.DateTime time { get; set; }
        public string status { get; set; }
        public System.DateTime tweetTime { get; set; }
        public string place { get; set; }
        public string city { get; set; }
        public string country { get; set; }
        public long sourcetweetid { get; set; }
        public double sourcelat { get; set; }
        public double sourcelong { get; set; }
        public string sourcecity { get; set; }
        public string sourcecountry { get; set; }
        public string userlocation { get; set; }
        public string sourceuserlocation { get; set; }
        public string entity_picurl { get; set; }
        public string entity_url1 { get; set; }
        public string entity_url2 { get; set; }
        public string lang_code { get; set; }
    }
}
