//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TweetLocalizationEF
{
    using System;
    using System.Collections.Generic;
    
    public partial class uniqueLocationFromTweetSample
    {
        public int id { get; set; }
        public string locationString { get; set; }
        public Nullable<bool> completelyProcessed { get; set; }
        public string gmaps { get; set; }
        public string bingmaps { get; set; }
        public string mapquest { get; set; }
    }
}
