//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace tweetLocalizerApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class BaseData
    {
        public BaseData()
        {
            this.KnowledgeBase = new HashSet<KnowledgeBase>();
        }
    
        public int Id { get; set; }
        public int BaseDataId { get; set; }
        public string AText { get; set; }
        public Nullable<double> ANumber { get; set; }
    
        public virtual ICollection<KnowledgeBase> KnowledgeBase { get; set; }
    }
}
