//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace tweetLocalizerApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Coordinates
    {
        public int Id { get; set; }
        public System.Data.Entity.Spatial.DbGeography Coord { get; set; }
        public Nullable<double> Longitude { get; set; }
        public Nullable<double> Latitude { get; set; }
        public int KnowledgeBaseId { get; set; }
    
        public virtual KnowledgeBase KnowledgeBase { get; set; }
    }
}
