//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace tweetLocalizerApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class GeoNames
    {
        public GeoNames()
        {
            this.alternateNames3 = new HashSet<alternateNames3>();
            this.countryinfo = new HashSet<countryinfo>();
            this.admin1Codes = new HashSet<admin1Codes>();
            this.admin2Codes = new HashSet<admin2Codes>();
        }
    
        public int geonameid { get; set; }
        public string name { get; set; }
        public string asciiname { get; set; }
        public string alternatenames { get; set; }
        public Nullable<double> latitude { get; set; }
        public Nullable<double> longitude { get; set; }
        public string feature_class { get; set; }
        public string feature_code { get; set; }
        public string country_code { get; set; }
        public string cc2 { get; set; }
        public string admin1_code { get; set; }
        public string admin2_code { get; set; }
        public string admin3_code { get; set; }
        public string admin4_code { get; set; }
        public Nullable<long> population { get; set; }
        public Nullable<int> elevation { get; set; }
        public Nullable<int> gtopo30 { get; set; }
        public string timezone { get; set; }
        public Nullable<System.DateTime> modification_date { get; set; }
        public System.Data.Entity.Spatial.DbGeography coord { get; set; }
    
        public virtual ICollection<alternateNames3> alternateNames3 { get; set; }
        public virtual ICollection<countryinfo> countryinfo { get; set; }
        public virtual timeZones timeZones { get; set; }
        public virtual countryinfo countryinfo1 { get; set; }
        public virtual ICollection<admin1Codes> admin1Codes { get; set; }
        public virtual ICollection<admin2Codes> admin2Codes { get; set; }
    }
}
