//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace tweetLocalizerApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class knowledgeBaseGeocoding
    {
        public int id { get; set; }
        public Nullable<int> knowledgeBaseId { get; set; }
        public Nullable<int> tweetRandomSampleId { get; set; }
        public Nullable<double> distanceToTweetCoordinates { get; set; }
        public System.Data.Entity.Spatial.DbGeography coord_knowledgeBaseResolution { get; set; }
        public System.Data.Entity.Spatial.DbGeography coord_tweet { get; set; }
        public string country_code { get; set; }
        public Nullable<int> NGramOrder { get; set; }
        public Nullable<int> NgramCount { get; set; }
    
        public virtual KnowledgeBase KnowledgeBase { get; set; }
        public virtual tweetRandomSample2 tweetRandomSample2 { get; set; }
    }
}
