//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace tweetLocalizerApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class KnowledgeBase
    {
        public KnowledgeBase()
        {
            this.Coordinates = new HashSet<Coordinates>();
            this.NGramItems = new HashSet<NGramItems>();
            this.KnowledgeBase1 = new HashSet<KnowledgeBase>();
            this.BaseData = new HashSet<BaseData>();
        }
    
        public int Id { get; set; }
        public string NGram { get; set; }
        public long NGramCount { get; set; }
        public int GeoNamesId { get; set; }
        public Nullable<int> CountryId { get; set; }
        public Nullable<int> Admin1Id { get; set; }
        public Nullable<int> Admin2Id { get; set; }
        public Nullable<int> Admin3Id { get; set; }
        public Nullable<int> Admin4Id { get; set; }
        public Nullable<int> FkIdAdditional { get; set; }
        public Nullable<int> ParentId { get; set; }
    
        public virtual ICollection<Coordinates> Coordinates { get; set; }
        public virtual ICollection<NGramItems> NGramItems { get; set; }
        public virtual ICollection<KnowledgeBase> KnowledgeBase1 { get; set; }
        public virtual KnowledgeBase KnowledgeBase2 { get; set; }
        public virtual ICollection<BaseData> BaseData { get; set; }
    }
}
