//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace tweetLocalizerApp
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class knowledgeObjects : DbContext
    {
        public knowledgeObjects()
            : base("name=knowledgeObjects")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Coordinates> Coordinates { get; set; }
        public virtual DbSet<KnowledgeBase> KnowledgeBase { get; set; }
        public virtual DbSet<NGramItems> NGramItems { get; set; }
        public virtual DbSet<NGramItemTypes> NGramItemTypes { get; set; }
        public virtual DbSet<BaseData> BaseData { get; set; }
    }
}
