//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace tweetLocalizerApp
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class knowledgeObjects : DbContext
    {
        public knowledgeObjects()
            : base("name=knowledgeObjects")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<KnowledgeBase> KnowledgeBase { get; set; }
        public virtual DbSet<NGramItems> NGramItems { get; set; }
        public virtual DbSet<BaseData> BaseData { get; set; }
        public virtual DbSet<learningBase> learningBase { get; set; }
        public virtual DbSet<tweetRandomSample2> tweetRandomSample2 { get; set; }
        public virtual DbSet<knowledgeBaseGeocoding> knowledgeBaseGeocoding { get; set; }
        public virtual DbSet<resultsKnowledgeBaseGeocoding> resultsKnowledgeBaseGeocoding { get; set; }
        public virtual DbSet<stopWordsAll> stopWordsAll { get; set; }
    
        [DbFunction("knowledgeObjects", "getSumOfNGramCounts")]
        public virtual IQueryable<Nullable<long>> getSumOfNGramCounts(Nullable<int> tweetRandomSampleId, Nullable<int> nGramOrder)
        {
            var tweetRandomSampleIdParameter = tweetRandomSampleId.HasValue ?
                new ObjectParameter("tweetRandomSampleId", tweetRandomSampleId) :
                new ObjectParameter("tweetRandomSampleId", typeof(int));
    
            var nGramOrderParameter = nGramOrder.HasValue ?
                new ObjectParameter("NGramOrder", nGramOrder) :
                new ObjectParameter("NGramOrder", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<Nullable<long>>("[knowledgeObjects].[getSumOfNGramCounts](@tweetRandomSampleId, @NGramOrder)", tweetRandomSampleIdParameter, nGramOrderParameter);
        }
    }
}
