//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace tweetLocalizerApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class resultsKnowledgeBaseGeocoding
    {
        public int id { get; set; }
        public Nullable<int> tweetRandomSampleId { get; set; }
        public Nullable<int> nGramOrder { get; set; }
        public Nullable<int> overallCount { get; set; }
        public Nullable<int> city_knowledgeBaseId { get; set; }
        public Nullable<int> city_geonamesId { get; set; }
        public Nullable<double> city_percentage { get; set; }
        public Nullable<int> adm2_knowledgeBaseId { get; set; }
        public Nullable<int> adm2_geonamesId { get; set; }
        public Nullable<double> adm2_percentage { get; set; }
        public Nullable<int> adm2_count { get; set; }
        public Nullable<int> adm2_loss { get; set; }
        public Nullable<int> adm1_knowledgeBaseId { get; set; }
        public Nullable<int> adm1_geonamesId { get; set; }
        public Nullable<double> adm1_percentage { get; set; }
        public Nullable<int> adm1_count { get; set; }
        public Nullable<int> adm1_loss { get; set; }
        public Nullable<int> country_knowledgeBaseId { get; set; }
        public Nullable<int> country_geonamesId { get; set; }
        public Nullable<double> country_percentage { get; set; }
        public Nullable<int> country_count { get; set; }
        public Nullable<int> city_count { get; set; }
    }
}
