//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace tweetLocalizerApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class timeZones
    {
        public timeZones()
        {
            this.cities1000 = new HashSet<cities1000>();
            this.cities15000 = new HashSet<cities15000>();
            this.cities5000 = new HashSet<cities5000>();
            this.GeoNames = new HashSet<GeoNames>();
        }
    
        public int ID { get; set; }
        public string country_code { get; set; }
        public string time_zone_id { get; set; }
        public Nullable<double> GMT_offset { get; set; }
        public Nullable<double> DST_offset { get; set; }
        public Nullable<double> rawOffset { get; set; }
    
        public virtual ICollection<cities1000> cities1000 { get; set; }
        public virtual ICollection<cities15000> cities15000 { get; set; }
        public virtual ICollection<cities5000> cities5000 { get; set; }
        public virtual ICollection<GeoNames> GeoNames { get; set; }
    }
}
