//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TwitterWebFrontend.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GeoNames_trs2_gmapsCoding
    {
        public string country_of_tweet_by_distance_method { get; set; }
        public string gmaps_country { get; set; }
        public int id { get; set; }
        public long tweetid { get; set; }
    }
}
