//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TwitterWebFrontend.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class geonamesid_geotreenodeidstring
    {
        public string nodeId { get; set; }
        public int GeoNames_geonamesid { get; set; }
    }
}
