//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TwitterWebFrontend.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class gmapsGeocoding
    {
        public int id { get; set; }
        public int tweetRandomSample2_Id { get; set; }
        public string formattedAddress { get; set; }
        public string resultStatus { get; set; }
        public Nullable<double> longitude { get; set; }
        public Nullable<double> latitude { get; set; }
        public string type { get; set; }
        public string country { get; set; }
        public System.Data.Entity.Spatial.DbGeography coord { get; set; }
        public Nullable<double> distance_to_tweet_coord { get; set; }
        public string country_by_ln_lat_from_tweet { get; set; }
        public string result_status_reverse { get; set; }
    
        public virtual tweetRandomSample2 tweetRandomSample2 { get; set; }
    }
}
