//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TwitterWebFrontend.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class manualAssign_tweetRandomSample2_to_geonamesRestricted
    {
        public int id { get; set; }
        public int tweetRandomSample2_id { get; set; }
        public Nullable<long> tweetId { get; set; }
        public bool is_unambiguously { get; set; }
        public Nullable<int> geoNamesRestricted_geonameid { get; set; }
        public string comment { get; set; }
        public string misc { get; set; }
    
        public virtual GeoNamesRestricted GeoNamesRestricted { get; set; }
        public virtual tweetRandomSample2 tweetRandomSample2 { get; set; }
    }
}
